name: rag-app
services:
  fastapi:
    container_name: fastapi
    build:
      context: ..
      dockerfile: docker/minirag/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - fastapi_data:/app/files
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - backend
    restart: always
    depends_on:
      - qdrant
      - mongodb
    env_file:
      - ../src/.env
  mongodb:
    image: mongo:7-jammy
    
    container_name: mongodb
    
    ports:
      - "27007:27017"
    
    volumes:
      - mongo_data:/data/db
    
    networks:
      - backend
    env_file:
      - ./.env
    
    restart: always
  # FastAPI Application
  qdrant:
    image: qdrant/qdrant:v1.13.6
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - backend
    restart: always


networks:
  backend:
    driver: bridge

volumes:
  fastapi_data:
  mongo_data:
  qdrant_data: